apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github 
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: 5863141e0f4b724b7c91 
      clientSecret: 
        name: github-client-secret
      hostname: ""  
      organizations: 
      - ezcorp
      teams: [] 
  - name: htpasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim 
    type: HTPasswd
