apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "vplugin/data/supersecret"
  name: htpasswd-secret
  namespace: openshift-config
data:
  htpasswd: <htpasswd_secret>
type: Opaque
